// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUIGDtVwmPF6RXajRgk7Pf-DQ8FVmOHns',
    appId: '1:420885151271:web:4fea5bdb215c9e7b5dd802',
    messagingSenderId: '420885151271',
    projectId: 'english-learning-35b9d',
    authDomain: 'english-learning-35b9d.firebaseapp.com',
    storageBucket: 'english-learning-35b9d.firebasestorage.app',
    measurementId: 'G-NFE1P5V0BB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-vi4_vmxAC-2so7NqtkKx7HiVDix3ar4',
    appId: '1:420885151271:android:8e578bc8d73abde55dd802',
    messagingSenderId: '420885151271',
    projectId: 'english-learning-35b9d',
    storageBucket: 'english-learning-35b9d.firebasestorage.app',
  );

}